<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <base href="">
    <title>Platform.AI</title>
    <meta name="author" content="Arshak Navruzyan">
    <meta name="description" content="Platform allows domain experts to produce high-quality labels for AI applications in minutes in a visual, interactive fashion.   It combines the latest research in human perception, active learning, transfer from pre-trained nets,  and noise-resilient training so that the labeler's time is used in the most productive way and the model learns from every  aspect of the human interaction.">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:300" rel="stylesheet"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"/>
    <link href="static/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/2.2.1/firebaseui.css" />
    <link type="text/css" rel="stylesheet" href="https://www.gstatic.com/firebasejs/ui/2.2.1/firebase-ui-auth.css" />

    <link type="text/css" rel="stylesheet" href="https://cdn.firebase.com/libs/firebaseui/3.4.1/firebaseui.css" />

  </head>
  <body>


<!-- Add your site or application content here -->
<p>---
title: Platform.AI
author: Arshak Navruzyan
email: arshak@platform.ai
description: Platform allows domain experts to produce high-quality labels for AI
  applications in minutes in a visual, interactive fashion.   It combines the latest
  research in human perception, active learning, transfer from pre-trained nets,  and
  noise-resilient training so that the labeler's time is used in the most productive
  way and the model learns from every  aspect of the human interaction.
baseurl: ''
url: https://platform.ai
defaults:
- scope:
    path: ''
  values:
    layout: default
markdown: kramdown
gems:
- jekyll-feed
- jekyll-menus
timezone: America/Los_Angeles
</p>

    <!--  Scripts-->
    <script src="https://js.stripe.com/v3/"></script>
    <script src="https://cdn.firebase.com/libs/firebaseui/3.4.1/firebaseui.js"></script>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="static/init.js"></script>      
  </body>
</html>